Fixed Hash compact no method error when compacting non-empty objects
Necessary to resolve the following exception due to `compact!`
answering `nil` when there is nothing to compact.

 NoMethodError:
       undefined method `delete_if' for nil:NilClass

This now matches behavior found with `Array.compact!` too.